/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package etl

class App {
    static void main(String[] args) {
        Properties props = Config.getAppProperties()
        props.keySet().toSorted().each {
            println("$it = ${props.getProperty(it)}")    
        }
    }
}
