/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package etl

class Demo {
    String getGreeting() {
        return 'Hello Gradle'
    }

    static void main(String[] args) {
        println new Demo().greeting
    }
}
